#!/bin/bash

cp ~/work/handday/crmZztx/crmZztx/pages/resources/js/constdefined.js ~/Desktop/constdefined.js

rm -r ~/work/handday/crmZztx/crmZztx/pages

cp -r ~/Library/Tomcat/webapps/WebProject/前端项目/MobileUI/IOS ~/work/handday/crmZztx/crmZztx/pages

mv ~/Desktop/constdefined.js ~/work/handday/crmZztx/crmZztx/pages/resources/js/constdefined.js

echo 'merge is done'