#!/bin/bash

#path1='/Users/zztx/study/myGithub/ruby/commonDefine.h'
path1='/Users/zztx/work/handday/crmZztx/crmZztx/Classes/Common/commonDefine.h'

#path2='/Users/zztx/study/myGithub/ruby/constdefined.js'
path2='/Users/zztx/work/handday/crmZztx/crmZztx/pages/resources/js/constdefined.js'

JS_DEFINE=LOCATION
TMP_FILE='/tmp/out.tmp.$$'

APP_DEFINE_STRING='#define APP_ENVIRONMENT_[^,]*$'
JS_DEFINE_STRING="var _type = __getUrlParam('rt') || RunTimeType.*";

case $1 in

dev)
sed "s/$APP_DEFINE_STRING/#define APP_ENVIRONMENT_$1/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$JS_DEFINE_STRING/var _type = __getUrlParam('rt') || RunTimeType.$JS_DEFINE;/g" $path2 > $TMP_FILE && mv $TMP_FILE $path2


cp /Users/zztx/work/handday/test/Default@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default@2x.png 
cp /Users/zztx/work/handday/test/Default-568h@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default-568h@2x.png 
;;

test)
JS_DEFINE=ONLINE_TEST
sed "s/$APP_DEFINE_STRING/#define APP_ENVIRONMENT_$1/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$JS_DEFINE_STRING/var _type = __getUrlParam('rt') || RunTimeType.$JS_DEFINE;/g" $path2 > $TMP_FILE && mv $TMP_FILE $path2

cp /Users/zztx/work/handday/test/Default@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default@2x.png 
cp /Users/zztx/work/handday/test/Default-568h@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default-568h@2x.png 
;;

online)
JS_DEFINE=ONLINE
sed "s/$APP_DEFINE_STRING/#define APP_ENVIRONMENT_$1/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$JS_DEFINE_STRING/var _type = __getUrlParam('rt') || RunTimeType.$JS_DEFINE;/g" $path2 > $TMP_FILE && mv $TMP_FILE $path2


cp /Users/zztx/work/handday/online/Default@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default@2x.png 
cp /Users/zztx/work/handday/online/Default-568h@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default-568h@2x.png 
;;
appstore)
JS_DEFINE=ONLINE
sed "s/$APP_DEFINE_STRING/#define APP_ENVIRONMENT_$1/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$JS_DEFINE_STRING/var _type = __getUrlParam('rt') || RunTimeType.$JS_DEFINE;/g" $path2 > $TMP_FILE && mv $TMP_FILE $path2


cp /Users/zztx/work/handday/online/Default@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default@2x.png 
cp /Users/zztx/work/handday/online/Default-568h@2x.png /Users/zztx/work/handday/crmZztx/crmZztx/resources/icon/Default-568h@2x.png 
;;
*)
echo 'Usage: dev|test|online|appstore'

;;
esac


#change app id

plistPath='/Users/zztx/work/handday/crmZztx/crmZztx/crmZztx-Info.plist'

if [ $1 = "appstore" ]
then
    sed "s/com.zztx.CRM/com.zztx.apple.CRM/g" $plistPath > $TMP_FILE && mv $TMP_FILE $plistPath
else
    sed "s/com.zztx.apple.CRM/com.zztx.CRM/g" $plistPath > $TMP_FILE && mv $TMP_FILE $plistPath
fi

exit 0


